services:
  phoenix_app:
    # change image and container name to phoenix_app_YOUR-PROJECT-NAME:base, to match what was built in the docker_files/.build_images.sh step
    image: hue-light-app
    container_name: hue-light-app
    hostname: hue-light-app
    depends_on:
      - database
    entrypoint: ["sh"] 
    ports:
      - "4200:4200"
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    volumes:
      - ./app_code:/opt/host_code # use to initially copy generated hello_world app
      #- ./app_code:/opt # after you copied the starter project to your host app_code folder
    environment:
      PGUSER: "nick"
      PGPASS: "nack"

  database:
    image: postgres:hue-light-app-DB
    container_name: hue-light-app-DB
    hostname: hue-light-app-DB
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_USER: "nick"
      POSTGRES_PASSWORD: "nack"
      POSTGRES_DB: "light-info"
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb

    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
